In [1]:
import os
import numpy as np
from sklearn.datasets import load_digits

In [2]:
mnist = load_digits()
mnist.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [3]:
mnist.data.shape

(1797, 64)

In [4]:
from sklearn.manifold import TSNE

In [5]:
tsne = TSNE(n_components=3, init='pca', learning_rate='auto')
tsne.fit(mnist.data)
tsne.embedding_.shape

C:\Users\Anirban_Haldar\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\manifold\_t_sne.py:991: FutureWarning: The PCA initialization in TSNE will change to have the standard deviation of PC1 equal to 1e-4 in 1.2. This will ensure better convergence.
  warnings.warn(


(1797, 3)

In [6]:
tsne.embedding_

array([[ -0.30651882,  21.944332  ,  -6.297458  ],
       [  9.776675  , -22.68747   ,   5.8799634 ],
       [ -1.4619721 ,  -3.932512  ,  -7.2229285 ],
       ...,
       [ -0.9918978 ,  -5.246236  ,  -1.1387115 ],
       [-17.20277   ,  17.572273  ,  -3.673666  ],
       [ -4.395225  ,  -3.4112117 ,   1.3749988 ]], dtype=float32)

In [7]:
import pandas as pd

In [18]:
df = pd.DataFrame(data=tsne.embedding_, columns=['x', 'y', 'z']).rename_axis(index="id")
df['label'] = mnist.target
df

x          y         z  label
id                                         
0     -0.306519  21.944332 -6.297458      0
1      9.776675 -22.687469  5.879963      1
2     -1.461972  -3.932512 -7.222929      2
3    -18.098791   2.847360 -1.750320      3
4     25.379896  -2.262954 -5.159170      4
...         ...        ...       ...    ...
1792 -19.014137  13.604458 -6.044274      9
1793   4.398367  19.226221 -6.896243      0
1794  -0.991898  -5.246236 -1.138711      8
1795 -17.202770  17.572273 -3.673666      9
1796  -4.395225  -3.411212  1.374999      8

[1797 rows x 4 columns]

In [19]:
from matplotlib import pyplot as plt

In [20]:
data = mnist.data
label = mnist.target

root = "mnist"
# os.mkdir(root)
all_files = []

for i in range(data.shape[0]):
    img = data[i]
    lab = str(label[i])
    folder = os.path.join(root, lab)
    # if not os.path.exists(folder): os.mkdir(folder)
    file = os.path.join(folder, f"{i}.png")
    # plt.imsave(file, data[i].reshape(8, 8).astype(np.int8), cmap="binary")
    all_files.append(file)

In [21]:
all_new_files = [x.replace('\\', '/') for x in all_files]
df['path'] = all_new_files
df.reset_index(inplace=True)
df

id          x          y         z  label              path
0        0  -0.306519  21.944332 -6.297458      0     mnist/0/0.png
1        1   9.776675 -22.687469  5.879963      1     mnist/1/1.png
2        2  -1.461972  -3.932512 -7.222929      2     mnist/2/2.png
3        3 -18.098791   2.847360 -1.750320      3     mnist/3/3.png
4        4  25.379896  -2.262954 -5.159170      4     mnist/4/4.png
...    ...        ...        ...       ...    ...               ...
1792  1792 -19.014137  13.604458 -6.044274      9  mnist/9/1792.png
1793  1793   4.398367  19.226221 -6.896243      0  mnist/0/1793.png
1794  1794  -0.991898  -5.246236 -1.138711      8  mnist/8/1794.png
1795  1795 -17.202770  17.572273 -3.673666      9  mnist/9/1795.png
1796  1796  -4.395225  -3.411212  1.374999      8  mnist/8/1796.png

[1797 rows x 6 columns]

In [22]:
df.to_json('mnist.js', orient='records')

In [54]:
mat = df[["x", "y", "z", "label"]].to_numpy().tolist()
len(mat)

1797

In [56]:
data = "data = " + str(mat)

with open("mnist.py", "w") as f:
    f.write(data)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
mat = np.array(mat)
data = mat[:, :3]
label = mat[:, 3].astype(int)
data, label

(array([[ -2.06711221,  22.28537369,  -5.80214739],
        [ 10.14194393, -22.5128231 ,   6.48842716],
        [  5.11270094,  -4.01964188,  -4.15704441],
        ...,
        [  0.51632339,  -4.8585844 ,  -1.00399065],
        [-14.49077511,  16.97520828,  -3.20830274],
        [ -2.38979983,  -2.00377393,   0.80017871]]),
 array([0, 1, 2, ..., 8, 9, 8]))

In [35]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(data, label)

KNeighborsClassifier()

In [46]:
x = 123

loc = data[x].reshape(1, -1)
dist, neigh = knn.kneighbors(loc)
dist, neigh = dist[0, 1:].tolist(), neigh[0, 1:].tolist()
dist, neigh

([0.7546715885640295, 1.721010348492222, 1.7460078713991956, 2.15181298742392],
 [249, 183, 248, 224])